/* Explicit project team assignments. Database policies decide administrator access. */
window.projectTeam={reset(){document.querySelectorAll('dialog.project-team-dialog').forEach(d=>{d.close();d.remove();});},async open(client,project){
 this.reset();const dialog=document.createElement('dialog');dialog.className='project-team-dialog';dialog.style.cssText='width:min(600px,95vw);border:0;border-radius:16px;padding:20px;max-height:85vh;overflow:auto';
 const title=document.createElement('h2');title.textContent='Команда · '+project.name;const close=document.createElement('button');close.className='smallbtn';close.textContent='Закрыть';close.onclick=()=>dialog.close();const status=document.createElement('p');status.textContent='Загрузка назначений…';dialog.append(title,status,close);document.body.append(dialog);dialog.addEventListener('close',()=>dialog.remove());dialog.showModal();
 try{
  const {data:auth,error:authError}=await client.auth.getUser();if(authError||!auth?.user)throw Error('Войдите в систему.');
  const [profiles,members,settings]=await Promise.all([client.from('profiles').select('id,full_name,role,is_active').order('full_name'),client.from('project_team_members').select('user_id,team_role,is_active').eq('project_id',project.id),client.rpc('get_project_settings',{p_project:project.id})]);
  if(profiles.error||members.error||settings.error)throw profiles.error||members.error||settings.error;let snapshot=settings.data;
  if(!dialog.isConnected)return;
  status.textContent='Назначения меняет подключённый директор. Ответственный объекта не заменяет состав команды.';
  const responsible=document.createElement('select');const empty=document.createElement('option');empty.value='';empty.textContent='Без ответственного';responsible.append(empty);for(const person of profiles.data.filter(p=>p.is_active)){const option=document.createElement('option');option.value=person.id;option.textContent=person.full_name||person.role;responsible.append(option);}responsible.value=snapshot.responsible_user_id||'';
  const responsibleRow=document.createElement('p'),responsibleSave=document.createElement('button');responsibleSave.className='smallbtn';responsibleSave.textContent='Сохранить ответственного';responsibleSave.onclick=async()=>{responsibleSave.disabled=true;try{await financialCommands.execute({kind:'responsible',project_id:project.id,user_id:responsible.value||null,expected:snapshot});const fresh=await client.rpc('get_project_settings',{p_project:project.id});if(fresh.error)throw fresh.error;snapshot=fresh.data;status.textContent='Ответственный сохранён. Доступ прорабов также определяется активными назначениями команды.';}catch(error){status.textContent='Не удалось изменить ответственного: '+error.message;}finally{responsibleSave.disabled=false;}};responsibleRow.append('Ответственный: ',responsible,' ',responsibleSave);dialog.insertBefore(responsibleRow,close);
  for(const profile of profiles.data.filter(p=>p.is_active&&p.role==='foreman')){
   const member=members.data.find(m=>m.user_id===profile.id);const row=document.createElement('p'),check=document.createElement('input');check.type='checkbox';check.checked=Boolean(member?.is_active);const label=document.createElement('label');label.append(check,' '+(profile.full_name||'Прораб'));const button=document.createElement('button');button.className='smallbtn';button.textContent='Сохранить';
   button.onclick=async()=>{button.disabled=true;try{await financialCommands.execute({kind:'assignment',project_id:project.id,user_id:profile.id,is_active:check.checked,expected:snapshot});const fresh=await client.rpc('get_project_settings',{p_project:project.id});if(fresh.error)throw fresh.error;snapshot=fresh.data;status.textContent=!check.checked&&snapshot.responsible_user_id===profile.id?'Назначение снято, но прораб остаётся ответственным и сохраняет доступ. Для полного снятия доступа измените ответственного.':'Назначение сохранено. Ответственный и финансовые данные объекта не изменены.';}catch(error){status.textContent='Не удалось сохранить: '+error.message;}finally{button.disabled=false;}};
   row.append(label,' ',button);dialog.insertBefore(row,close);
  }
 }catch(error){status.textContent='Не удалось загрузить команду: '+error.message;}
}};
