let ksImportPreview=null,ksDirectorSubmissions=[];
function ksDirector(){return profile?.role==='director';}
window.renderWorkItems=function(){
 const rows=projectWorkItems.filter(w=>w.project_id===currentWorkProjectId);
 $('ksImportPanel').style.display=ksDirector()?'block':'none';
 $('ksSubmissionsPanel').style.display=ksDirector()?'block':'none';
 $('workItemsList').innerHTML=rows.length?rows.map(w=>{const fact=workCompletedTotal(w.id),plan=Number(w.planned_volume||0),pct=workItemPct(w),progress=workProgressRowsFor(w.id),mats=workMaterialRowsFor(w.id),section=projectWorkSections.find(s=>s.id===w.section_id),rate=ksDirector()?projectWorkRates.find(r=>r.work_item_id===w.id):null,doc=projectDocuments.find(d=>d.id===w.source_document_id);return `<div class="work-item"><div class="row"><div><b>${esc(w.work_name)}</b> ${w.is_active===false?'<span class="status-tag p-orange">Архивная строка</span>':''}<div class="muted">${section?'Раздел: '+esc(section.name)+' · ':''}План: ${plan.toLocaleString('ru-RU')} ${esc(w.unit)} · Утверждено: ${fact.toLocaleString('ru-RU')} ${esc(w.unit)} · Остаток: ${(plan-fact).toLocaleString('ru-RU')} ${esc(w.unit)}</div></div><span class="status-tag ${pct>=100?'p-green':'p-blue'}">${pct.toFixed(0)}%</span></div><div class="muted" style="margin-top:6px">Основание: ${esc(w.basis_label||'внесено ранее')}${doc?' · '+esc(doc.title||doc.file_name||'Файл'):''}${w.source_locator?' · '+esc(w.source_locator):''}</div>${w.display_description?`<div class="muted">Пояснение: ${esc(w.display_description)}</div>`:''}${rate?`<div class="muted">Расценка директора: ${Number(rate.unit_rate).toLocaleString('ru-RU')} ₽ / ${esc(w.unit)}</div>`:''}<details><summary>История выполнения (${progress.length})</summary>${progress.map(p=>`<div class="subrow"><span>${fmtDate(p.progress_date)} · ${esc(p.comment||'')}</span><b>+${Number(p.completed_volume).toLocaleString('ru-RU')} ${esc(w.unit)}</b></div>`).join('')||'<div class="muted">Утверждённых фактов нет.</div>'}</details><details><summary>Исторические материалы (${mats.length})</summary>${mats.map(m=>`<div class="subrow">${esc(m.material_name)} · ${Number(m.quantity).toLocaleString('ru-RU')} ${esc(m.unit)}</div>`).join('')||'<div class="muted">Нет материалов.</div>'}</details>${ksDirector()?`<div class="work-task-actions"><button class="smallbtn" onclick="openWorkItemForm('${w.id}')">Изменить</button><button class="smallbtn" onclick="openWorkProgressForm('${w.id}')">＋ Ручной факт</button>${w.is_active!==false?`<button class="smallbtn" onclick="completeWorkItem('${w.id}')">✓ Завершить</button><button class="smallbtn" style="color:#b42318" onclick="deleteWorkItem('${w.id}')">Удалить</button>`:''}</div>`:''}</div>`;}).join(''):'<div class="empty">Работ пока нет. Директор может добавить их из документа или вручную.</div>';
};
function openKsImport(){
 if(!ksDirector())return alert('Перечень из документов подтверждает только директор.');
 const docs=projectDocuments.filter(d=>d.project_id===currentWorkProjectId);
 if(!docs.length)return alert('Сначала загрузите PDF, DOCX или XLSX в «Документы» этого объекта.');
 $('ksImportDocument').innerHTML=docs.map(d=>`<option value="${d.id}">${esc(d.title||d.file_name||'Документ')} · ${esc(d.file_name||'')}</option>`).join('');
 $('ksImportBasis').value='Основная смета';$('ksImportRows').innerHTML='';$('ksImportWarnings').textContent='';ksImportPreview=null;
 $('ksImportModal').classList.add('open');loadKsImportVersions();
}
function closeKsImport(){$('ksImportModal').classList.remove('open');ksImportPreview=null;}
async function loadKsImportVersions(){const id=$('ksImportDocument').value;const {data,error}=await sbClient.from('project_document_versions').select('id,version_no,file_name').eq('document_id',id).order('version_no',{ascending:false});if(error)return alert('Версии документа недоступны: '+error.message);if(id!==$('ksImportDocument').value)return;$('ksImportVersion').innerHTML=(data||[]).map(v=>`<option value="${v.id}">Версия ${v.version_no} · ${esc(v.file_name||'файл')}</option>`).join('');}
async function analyzeKsImport(){
 if(!ksDirector())return;const documentId=$('ksImportDocument').value,versionId=$('ksImportVersion').value,basis=$('ksImportBasis').value.trim();
 if(!documentId||!versionId||!basis)return alert('Выберите документ, версию и тип основания.');
 $('ksImportWarnings').textContent='Читаю файл и собираю предпросмотр…';$('ksImportRows').innerHTML='';
 const {data,error}=await sbClient.functions.invoke('work-document',{body:{project_id:currentWorkProjectId,document_id:documentId,version_id:versionId,basis_label:basis}});
 if(error||data?.error){$('ksImportWarnings').textContent='Разбор не выполнен: '+(data?.error||error?.message||'ошибка');return;}
 ksImportPreview=data.preview;renderKsImportRows();
}
function ksImportRowMarkup(row,i){const old=Boolean(row.old_work_id),checked=Boolean(row.include),kind=row.kind||'work';return `<div class="work-item" data-ks-row="${i}" style="margin:7px 0;padding:10px"><div><b>${i+1}. ${esc(row.locator||'Ручная строка')}</b> ${old?'<span class="muted">Ранее принятая строка</span>':''}</div><div class="muted">Источник: ${esc(row.source_quote||'добавлено вручную')}</div><div class="field"><label>Тип строки</label><select class="ks-kind">${['work','material','equipment','heading','note','total','unreadable'].map(x=>`<option value="${x}" ${kind===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Название точно по документу</label><input class="ks-name" maxlength="1000" value="${esc(row.name||'')}"></div><div style="display:flex;gap:7px;flex-wrap:wrap"><div class="field" style="flex:1"><label>Единица</label><input class="ks-unit" maxlength="100" value="${esc(row.unit||'')}"></div><div class="field" style="flex:1"><label>Плановый объём</label><input class="ks-qty" type="number" step="0.001" min="0" value="${row.quantity??''}"></div></div><div class="field"><label>Раздел</label><input class="ks-section" maxlength="300" value="${esc(row.section||'')}"></div><div class="field"><label>Понятное пояснение</label><input class="ks-description" maxlength="1000" value="${esc(row.description||'')}"></div><label><input class="ks-include" type="checkbox" ${checked?'checked':''}> Включить в перечень${old?' с заменой прежней строки':''}</label>${row.questions?.length?`<div style="color:#b42318">${row.questions.map(esc).join('; ')}</div>`:''}</div>`;}
function renderKsImportRows(){const p=ksImportPreview;if(!p)return;const warnings=p.warnings||[],committed=p.status==='committed';$('ksImportWarnings').textContent=`Файл действительно прочитан. Строк: ${p.rows.length}. ${committed?'Эта версия уже принята; повторная запись закрыта. Для изменений загрузите новую версию файла.':warnings.length?`Замечания (${warnings.length}): ${warnings.slice(0,12).join(' ')}`:'Проверьте источник, названия, единицы и объёмы каждой строки.'}`;
 $('ksImportRows').innerHTML=`<div class="muted">Каждая строка показана, включая заголовки, материалы и итоги. Перед включением проверьте тип, название, единицу и объём. Расценки из файла не переносятся.</div>`+p.rows.map(ksImportRowMarkup).join('')+(committed?'':`<button class="smallbtn" onclick="addKsImportRow()">＋ Добавить строку вручную</button><button class="btn primary" style="margin-top:10px" onclick="saveKsImportPreview()">Сохранить исправления и решения</button><button class="btn primary" style="margin-top:10px" onclick="commitKsImport()">Подтвердить перечень работ</button>`);if(committed)$('ksImportRows').querySelectorAll('input,select').forEach(el=>el.disabled=true);}
function addKsImportRow(){if(!ksImportPreview)return;ksImportPreview.rows.push({key:'manual-'+crypto.randomUUID(),kind:'work',name:'',unit:'',quantity:null,section:'',description:'',include:false,decision:'exclude',locator:'Добавлено директором при проверке',source_quote:null,questions:[]});renderKsImportRows();const row=$('ksImportRows').querySelector(`[data-ks-row="${ksImportPreview.rows.length-1}"]`);row?.scrollIntoView({block:'center'});}
function collectKsImportRows(){return ksImportPreview.rows.map((r,i)=>{const el=$('ksImportRows').querySelector(`[data-ks-row="${i}"]`);if(!el)throw Error('Не все строки показаны.');const include=el.querySelector('.ks-include').checked,quantity=el.querySelector('.ks-qty').value;return {key:r.key,kind:el.querySelector('.ks-kind').value,name:el.querySelector('.ks-name').value.trim(),unit:el.querySelector('.ks-unit').value.trim(),quantity:quantity===''?null:Number(quantity),section:el.querySelector('.ks-section').value.trim()||null,description:el.querySelector('.ks-description').value.trim()||null,include,decision:include?(r.old_work_id?'supersede':'add'):(r.old_work_id&&r.decision==='keep'?'keep':'exclude')};});}
async function saveKsImportPreview(){if(!ksDirector()||!ksImportPreview)return;let rows;try{rows=collectKsImportRows();}catch(e){return alert(e.message);}const {data,error}=await sbClient.rpc('ks_edit_import_preview',{p_preview:ksImportPreview.id,p_expected:ksImportPreview.updated_at,p_rows:rows});if(error)return alert('Исправления не сохранены: '+error.message);ksImportPreview=data;renderKsImportRows();alert('Исправления сохранены. Проверьте строки и подтвердите перечень.');}
async function commitKsImport(){if(!ksDirector()||!ksImportPreview)return;let rows;try{rows=collectKsImportRows();}catch(e){return alert(e.message);}if(rows.some((r,i)=>r.name!==ksImportPreview.rows[i]?.name||r.kind!==ksImportPreview.rows[i]?.kind||r.unit!==ksImportPreview.rows[i]?.unit||Number(r.quantity)!==Number(ksImportPreview.rows[i]?.quantity)||r.include!==ksImportPreview.rows[i]?.include||r.section!==(ksImportPreview.rows[i]?.section||null)||r.description!==(ksImportPreview.rows[i]?.description||null)||r.decision!==ksImportPreview.rows[i]?.decision))return alert('Сначала нажмите «Сохранить исправления и решения».');const count=rows.filter(r=>r.include).length;if(!count)return alert('Ни одна работа не включена.');if(!confirm(`Записать ${count} подтверждённых строк в перечень объекта? Разделы будут созданы по указанным названиям.`))return;
 const {data,error}=await sbClient.rpc('ks_commit_import',{p_request:crypto.randomUUID(),p_preview:ksImportPreview.id,p_expected:ksImportPreview.updated_at});if(error)return alert('Перечень не записан: '+error.message);closeKsImport();await loadAll();renderWorkPanel();alert('Подтверждено и записано строк: '+(data.rows?.length||0)+'. Расценки можно ввести только вручную в карточке работы.');}

async function openKsSubmissions(){if(!ksDirector())return alert('Проверка подач доступна только директору.');$('ksSubmissionsModal').classList.add('open');await refreshKsSubmissions();}
function closeKsSubmissions(){$('ksSubmissionsModal').classList.remove('open');}
async function refreshKsSubmissions(){const {data,error}=await sbClient.rpc('ks_project_submissions',{p_project:currentWorkProjectId});if(error){$('ksSubmissionRows').textContent='Очередь недоступна: '+error.message;return;}ksDirectorSubmissions=data||[];renderKsSubmissions();}
function ksStatusLabel(s){return ({pending_review:'На проверке у директора',returned:'Возвращена прорабу',approved:'Подтверждена',submitted:'Ранее внесена'})[s]||s;}
function renderKsSubmissions(){$('ksSubmissionRows').innerHTML=ksDirectorSubmissions.length?ksDirectorSubmissions.map((bundle,index)=>{const s=bundle.submission,items=bundle.items||[],pending=s.status==='pending_review',overrun=s.overrun_requested;return `<div class="work-item" style="margin:9px 0"><b>Подача № ${s.submission_no||'—'}</b> · ${esc(ksStatusLabel(s.status))}<div class="muted">${fmtDate(s.period_from)} — ${fmtDate(s.period_to)} · прораб ${esc(s.created_by||'—')} · отправлено ${esc(s.created_at||'—')}</div>${s.review_note?`<div class="muted">Замечание: ${esc(s.review_note)}</div>`:''}<div style="margin-top:8px">${items.map(i=>`<div class="subrow"><div>${esc(i.work_name)}<div class="muted">${esc(i.basis_label||'внесено ранее')}</div></div><b>${Number(i.volume).toLocaleString('ru-RU')} ${esc(i.unit)}</b></div>`).join('')}</div>${pending?`<div class="muted">На проверке: эти объёмы ещё не вошли в факт. Сверьте остатки и другие ожидающие подачи.</div><label style="display:${overrun?'block':'none'}"><input type="checkbox" id="ksOverrun${index}"> Я рассмотрел превышение остатка и разрешаю его</label><label><input type="checkbox" id="ksConflict${index}"> Я рассмотрел возможное двойное закрытие с другими подачами</label><div class="work-task-actions"><button class="smallbtn" onclick="decideKsSubmission(${index},'approve')">✅ Подтвердить</button><button class="smallbtn" onclick="decideKsSubmission(${index},'return')">↩ Вернуть на доработку</button></div>`:''}<div class="work-task-actions"><button class="smallbtn" onclick="downloadKsSubmission(${index})">Сохранить документ подачи</button></div><details><summary>История версий (${(bundle.revisions||[]).length})</summary>${(bundle.revisions||[]).map(r=>`<div class="muted">Версия ${r.version_no} · ${esc(ksStatusLabel(r.status))} · ${esc(r.created_at)}${r.note?' · '+esc(r.note):''}</div>`).join('')}</details></div>`;}).join(''):'<div class="empty">Подач объёмов для этого объекта пока нет.</div>';}
async function decideKsSubmission(index,decision){if(!ksDirector())return;const bundle=ksDirectorSubmissions[index],s=bundle?.submission;if(!s||s.status!=='pending_review')return alert('Подача изменилась. Обновите очередь.');let note=null;if(decision==='return'){note=prompt('Укажите конкретную причину возврата и требуемые исправления:');if(note===null)return;if(!note.trim())return alert('Причина обязательна.');}else if(!confirm(`Подтвердить подачу № ${s.submission_no}? Только после этого объёмы войдут в утверждённый факт.`))return;
 const {data,error}=await sbClient.rpc('ks_review_submission',{p_request:crypto.randomUUID(),p_submission:s.id,p_expected:s.updated_at,p_decision:decision,p_note:note,p_accept_overrun:document.getElementById('ksOverrun'+index)?.checked||false,p_accept_pending_conflict:document.getElementById('ksConflict'+index)?.checked||false});
 if(error)return alert('Решение не записано: '+error.message);await loadAll();renderWorkPanel();await refreshKsSubmissions();alert('Подача № '+data.submission_no+': '+ksStatusLabel(data.status)+'.');}
function downloadKsSubmission(index){const bundle=ksDirectorSubmissions[index],s=bundle?.submission;if(!s)return;const project=projects.find(p=>p.id===s.project_id);const html=`<!doctype html><meta charset="utf-8"><title>Подача объёмов № ${s.submission_no}</title><style>body{font:16px Arial;margin:30px}table{border-collapse:collapse;width:100%}td,th{border:1px solid #888;padding:7px;text-align:left}</style><h1>Подача объёмов для подготовки КС № ${s.submission_no}</h1><p>Объект: ${esc(project?.name||'—')}<br>Период: ${esc(s.period_from)} — ${esc(s.period_to)}<br>Прораб: ${esc(s.created_by)}<br>Статус: ${esc(ksStatusLabel(s.status))}<br>Проверил: ${esc(s.reviewed_by||'—')} · ${esc(s.reviewed_at||'—')}</p><table><thead><tr><th>Работа</th><th>Основание</th><th>Ед.</th><th>Объём</th></tr></thead><tbody>${(bundle.items||[]).map(i=>`<tr><td>${esc(i.work_name)}</td><td>${esc(i.basis_label)}</td><td>${esc(i.unit)}</td><td>${Number(i.volume).toLocaleString('ru-RU')}</td></tr>`).join('')}</tbody></table><p>Это подача для подготовки КС, а не утверждённая КС-2/КС-3 заказчику.</p>`;const url=URL.createObjectURL(new Blob([html],{type:'text/html;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`Подача объёмов № ${s.submission_no}.html`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
