const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
class Element{constructor(){this.value='';this.children=[];this.handlers={};this.classList={contains:()=>true};this.scrollHeight=100;this.scrollTop=50;this.clientHeight=100;}append(...x){this.children.push(...x);}replaceChildren(...x){this.children=x;}setAttribute(k,v){this[k]=v;}addEventListener(k,f){this.handlers[k]=f;}}
const elements={},tables={agent_conversations:[{id:'chat-a',owner_id:'a',title:'A private',last_message_at:new Date().toISOString()},{id:'chat-b',owner_id:'b',title:'B private',last_message_at:new Date().toISOString()}],agent_chat_messages:[],agent_activity_events:[],agent_protocol_entries:[]};
let serial=0,user='a',delayReply=false,resolveReply,voiceCalls=0,stopped=0,answerDeadline=null;const inserted=[];let testApprovals=[],lastApproval=null;
const stamp=()=>new Date(Date.now()+serial++).toISOString(),tick=()=>new Promise(r=>setImmediate(r));
const client={functions:{invoke:async(name,{body})=>{if(body?.operation==='list_approvals')return {data:{approvals:testApprovals}};if(name==='transcribe-voice'){voiceCalls++;assert.equal(body.get('chat_id'),'chat-a');return {data:{text:'По объекту один поступило десять тысяч рублей.'}};}if(delayReply)return new Promise(r=>resolveReply=r);if(body.approval){lastApproval=body.approval;testApprovals=[];}const source=tables.agent_chat_messages.find(m=>m.id===body.message_id);const reply={id:'reply-'+serial++,owner_id:source.owner_id,chat_id:source.chat_id,kind:'assistant',content:'Ответ агента',created_at:stamp()};tables.agent_chat_messages.push(reply);return {data:{message:reply}};}},from(table){return {
 select(){const filters=[];const q={eq(k,v){filters.push([k,v]);return q;},order(){return q;},range(){assert(filters.some(([k])=>k==='chat_id'));return get();},limit(){return get();}};function get(){return Promise.resolve({data:tables[table].filter(x=>filters.every(([k,v])=>x[k]===v)),error:null});}return q;},
 insert(payload){assert.equal(payload.owner_id,user);const row={...payload,created_at:stamp(),last_message_at:stamp()};tables[table].push(row);if(table==='agent_chat_messages')inserted.push(payload);return {select(){return {single:async()=>({data:row,error:null})}}};}
 };}};
class Recorder{static isTypeSupported(){return true;}constructor(){this.state='inactive';}start(){this.state='recording';}stop(){this.state='inactive';this.ondataavailable({data:new Blob([new Uint8Array(200)],{type:'audio/webm'})});this.onstop();}}
const storage=new Map();const ctx={window:{},sbClient:client,crypto:{randomUUID:()=>String(serial++)},document:{visibilityState:'visible',getElementById:id=>elements[id]??=new Element(),createElement:()=>new Element()},setInterval:()=>1,clearInterval(){},setTimeout:(fn,ms)=>{if(ms===130000)answerDeadline=fn;return 1;},clearTimeout(){},localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},navigator:{mediaDevices:{getUserMedia:async()=>({getTracks:()=>[{stop(){stopped++;}}]})}},MediaRecorder:Recorder,FormData,Blob};
vm.createContext(ctx);vm.runInContext(fs.readFileSync('chat.js','utf8'),ctx);
(async()=>{
 const chat=ctx.window.financeChat;await chat.init({user:{id:'a'}});elements.agentChatInput.value='<img src=x onerror=alert(1)>';await chat.send();
 assert.equal(inserted[0].chat_id,'chat-a');assert.equal(elements.agentChatInput.value,'');assert.equal(elements.agentChatMessages.children[0].children[1].textContent,'<img src=x onerror=alert(1)>');assert.equal(elements.agentChatMessages.children[0].children[1].children.length,0);
 const old=inserted.length;elements.agentChatInput.handlers.keydown({key:'Enter',shiftKey:true,preventDefault(){throw Error('shift blocked');}});elements.agentChatInput.handlers.beforeinput({inputType:'insertLineBreak',preventDefault(){throw Error('Shift newline blocked');}});assert.equal(inserted.length,old);elements.agentChatInput.handlers.keydown({key:'Enter',isComposing:true,preventDefault(){throw Error('IME blocked');}});assert.equal(inserted.length,old);
 elements.agentChatInput.value='Enter send';let prevented=false;elements.agentChatInput.handlers.keydown({key:'Enter',preventDefault(){prevented=true;}});await tick();assert(prevented);assert.equal(inserted.at(-1).content,'Enter send');
 elements.agentChatInput.value='Phone send';elements.agentChatInput.handlers.beforeinput({inputType:'insertParagraph',preventDefault(){}});await tick();assert.equal(inserted.at(-1).content,'Phone send');
 await chat.voice();await chat.voice();await tick();assert.equal(voiceCalls,1);assert.equal(inserted.at(-1).source,'voice');assert(inserted.at(-1).content.includes('десять тысяч'));assert(stopped>0);
 await chat.voice();chat.cancelVoice();await tick();assert.equal(voiceCalls,1);
 await chat.newChat();assert(!elements.agentChatMessages.children.some(x=>x.children?.[1]?.textContent==='Enter send'));assert.equal(elements.agentChatHistoryList.children.length,2);
 delayReply=true;elements.agentChatInput.value='Late answer';const pending=chat.send();await tick();chat.reset();user='b';await chat.init({user:{id:'b'}});resolveReply({data:{message:{id:'late',kind:'assistant',content:'A secret late answer',created_at:stamp()}}});await pending;
 assert.equal(elements.agentChatHistoryList.children.length,1);assert(!elements.agentChatMessages.children.some(x=>x.children?.[1]?.textContent==='A secret late answer'));
 elements.agentChatInput.value='Timeout';const timed=chat.send();await tick();answerDeadline();await timed;assert.equal(elements.agentChatSend.disabled,false);assert(elements.agentChatStatus.textContent.includes('Ожидание ответа'));const count=inserted.length;resolveReply({data:{message:{id:'late-timeout',kind:'assistant',content:'Delayed',created_at:stamp()}}});await tick();assert.equal(inserted.length,count);assert(!elements.agentChatMessages.children.some(x=>x.children?.[1]?.textContent==='Delayed'));delayReply=false;
 testApprovals=[{id:'11111111-1111-4111-8111-111111111111',version:'revision-A',description:'Приход 50 000 ₽ по ЖК Ёлки',expires_at:stamp()}];await chat.refresh();
 const panel=elements.agentChatMessages.children.at(-1),approve=panel.children.find(x=>x?.textContent==='Подтвердить');assert(approve);const prior=inserted.length;approve.onclick();approve.onclick();await tick();assert.equal(inserted.length,prior+1);assert.equal(lastApproval.version,'revision-A');assert.equal(elements.agentChatInput.value,'');assert(elements.agentChatMessages.children.some(x=>x.children?.[1]?.textContent==='Подтверждаю выбранный план.'));
 chat.reset();assert.equal(elements.agentChatMessages.children.length,0);assert.equal(elements.agentChatSend.disabled,true);
 const html=fs.readFileSync('index.html','utf8');for(const b of html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script\s*>/gi))if(!b[1].includes('src=')&&!b[1].includes('type="module"'))new vm.Script(b[2]);assert(html.includes('enterkeyhint="send"'));assert(html.indexOf('src="chat.js?')<html.indexOf('const SUPABASE_URL'));
 console.log('PASS: owner/thread filtering, new/private history, text safety, Enter/mobile/Shift/IME, voice transcription and cancellation, mic release, stale reply and logout');
})().catch(e=>{console.error(e);process.exitCode=1});
