do $test$
declare actor uuid:=gen_random_uuid();foreman uuid:=gen_random_uuid();pid uuid:=gen_random_uuid();foreign_pid uuid:=gen_random_uuid();snapshot jsonb;cmd jsonb;r jsonb;request uuid:=gen_random_uuid();denied boolean;chat uuid:=gen_random_uuid();msg uuid:=gen_random_uuid();confirmation uuid:=gen_random_uuid();plan jsonb;
begin
 begin
 insert into auth.users(id) values(actor),(foreman);insert into public.profiles(id,role,is_active) values(actor,'director',true),(foreman,'foreman',true);insert into public.agent_director_access values(actor);insert into public.projects(id,name) values(pid,'TEST assignments'),(foreign_pid,'TEST foreign assignment');perform set_config('request.jwt.claim.sub',actor::text,true);
 snapshot:=public.get_project_settings(pid);cmd:=jsonb_build_object('kind','assignment','project_id',pid,'user_id',foreman,'is_active',true,'expected',snapshot);
 if voltmaster_private.project_settings_command(actor,request,cmd,true)->'before' is distinct from snapshot or exists(select 1 from public.project_team_members where project_id=pid) then raise exception 'Assignment preview wrote';end if;
 execute 'set local role authenticated';r:=public.execute_project_settings(request,cmd);execute 'reset role';if r->>'verified'<>'true' then raise exception 'Assignment verify';end if;
 if public.execute_project_settings(request,cmd) is distinct from r then raise exception 'Assignment replay';end if;
 denied:=false;begin perform public.execute_project_settings(gen_random_uuid(),cmd);exception when others then denied:=sqlerrm='Project settings changed; reload';end;if not denied then raise exception 'Stale assignment';end if;
 perform set_config('request.jwt.claim.sub',foreman::text,true);execute 'set local role authenticated';if not exists(select 1 from public.foreman_projects() where id=pid) or exists(select 1 from public.foreman_projects() where id=foreign_pid) then raise exception 'Assignment scope';end if;execute 'reset role';
 r:=public.execute_production_command(gen_random_uuid(),jsonb_build_object('kind','foreman_subcontractor','action','create','values',jsonb_build_object('project_id',pid,'name','TEST basic foreman')));if r->'record' ? 'planned_amount' then raise exception 'Foreman financial disclosure';end if;
 denied:=false;begin perform public.execute_production_command(gen_random_uuid(),jsonb_build_object('kind','foreman_subcontractor','action','create','values',jsonb_build_object('project_id',foreign_pid,'name','TEST foreign')));exception when others then denied:=true;end;if not denied then raise exception 'Foreman foreign create';end if;
 denied:=false;begin perform public.execute_project_settings(gen_random_uuid(),cmd);exception when others then denied:=sqlerrm='Trusted director required';end;if not denied then raise exception 'Foreman changed own access';end if;
 perform set_config('request.jwt.claim.sub',actor::text,true);snapshot:=public.get_project_settings(pid);
 cmd:=jsonb_build_object('kind','volume_rule','project_id',pid,'expected',snapshot,'config',jsonb_build_object('project_id',pid,'assignee_id',foreman,'expected_version',null,'due_day',25,'reminder_time','10:00','short_month_policy','last_day','period_offset',-1,'enabled',true,'authority_basis','TEST explicit director instruction'));
 insert into public.agent_conversations(id,owner_id,title) values(chat,actor,'TEST settings');insert into public.agent_chat_messages(id,owner_id,chat_id,kind,content) values(msg,actor,chat,'user','TEST rule');
 execute 'set local role service_role';plan:=public.agent_prepare_operator_plan(actor,chat,msg,'project_settings_write',cmd);execute 'reset role';if exists(select 1 from voltmaster_private.volume_rules where project_id=pid) then raise exception 'Rule preview wrote';end if;
 insert into public.agent_chat_messages(id,owner_id,chat_id,kind,content) values(confirmation,actor,chat,'user','ПОДТВЕРЖДАЮ '||(plan->>'id'));execute 'set local role service_role';r:=public.agent_execute_operator_plan(actor,(plan->>'id')::uuid,(plan->>'revision')::uuid,confirmation);execute 'reset role';if r->'result'->>'verified'<>'true' or not exists(select 1 from voltmaster_private.volume_rules where project_id=pid and assignee_id=foreman and due_day=25) then raise exception 'Rule confirmation';end if;
 snapshot:=public.get_project_settings(pid);perform public.execute_project_settings(gen_random_uuid(),jsonb_build_object('kind','assignment','project_id',pid,'user_id',foreman,'is_active',false,'expected',snapshot));perform set_config('request.jwt.claim.sub',foreman::text,true);execute 'set local role authenticated';if exists(select 1 from public.foreman_projects() where id=pid) then raise exception 'Revoked assignment still visible';end if;execute 'reset role';
 raise exception using errcode='P0992',message='ROLLBACK_SETTINGS';exception when sqlstate 'P0992' then null;end;
end $test$;
select 'PASS: assignments/revocation use actual RLS, fresh snapshot and replay; foreman basic adapter hides money; real regulation plan confirmation, previews rolled back; fixtures rolled back' result;
