const vm=require('node:vm'),assert=require('node:assert/strict');const source=require('./load-edge.cjs').mainSource();
const id='11111111-1111-4111-8111-111111111111',revision='22222222-2222-4222-8222-222222222222';
async function scenario({operation=false,version=revision,role='finance',active=true,ownChat=true,natural=false,planCount=1}={}){
 const calls=[],plan={id,revision,kind:'operation_write',command_json:{action:'create'},preview_json:{operation:{operation_type:'income',operation_date:'2026-10-06',amount:50000,payer_company:'ИП',article:'Аванс заказчика',counterparty:null},before:null,related:[]},expires_at:'2026-10-06T23:59:00Z'};
 const ctx={Response,AbortSignal,TextDecoder,TextEncoder,crypto:require('node:crypto').webcrypto,Deno:{env:{get:()=> 'test'}},fetch:async(url,options={})=>{calls.push({url,options});const reply=v=>new Response(JSON.stringify(v));if(url.includes('/auth/v1/user'))return reply({id});if(url.includes('/profiles?'))return reply([{role,is_active:active}]);if(url.includes('/agent_director_access?'))return reply(role==='director'?[{user_id:id}]:[]);if(url.includes('/agent_conversations?'))return reply(ownChat?[{id}]:[]);if(url.includes('/agent_operator_plans?'))return reply(Array.from({length:planCount},()=>plan));if(url.includes('/agent_chat_messages?'))return reply([{id,chat_id:id,kind:'user',content:natural?'подтверждаю':'ПОДТВЕРЖДАЮ '+id}]);if(url.includes('rpc/agent_execute_operator_plan'))return reply({status:'completed',result:{verified:true,action:'create',operation:plan.preview_json.operation}});if(url.endsWith('/agent_chat_messages'))return reply([{id,...JSON.parse(options.body)}]);throw Error('Unexpected route '+url);}};
 vm.createContext(ctx);vm.runInContext(source,ctx);const res=await ctx.handle(new Request('https://test',{method:'POST',headers:{Authorization:'Bearer user'},body:JSON.stringify(operation?{operation:'list_approvals',chat_id:id}:{message_id:id,approval:{id,version}})}));return {status:res.status,body:await res.json(),calls};
}
(async()=>{
 const listed=await scenario({operation:true});assert.equal(listed.status,200);assert.equal(listed.body.approvals[0].version,revision);assert(listed.body.approvals[0].description.includes('50 000'));assert(!listed.body.approvals[0].description.includes('undefined'));assert(listed.calls.every(x=>!x.url.includes('openai.com')));assert(listed.calls.filter(x=>x.url.includes('/agent_operator_plans?')).every(x=>x.url.includes('owner_id=eq.'+id)&&x.url.includes('chat_id=eq.'+id)));
 assert.equal((await scenario({operation:true,ownChat:false})).status,404);assert.deepEqual((await scenario({operation:true,role:'foreman'})).body.approvals,[]);
 const approved=await scenario();assert.equal(approved.status,200);assert.equal(approved.body.data_changed,true);assert(approved.calls.some(x=>x.url.includes('rpc/agent_execute_operator_plan')));assert(!approved.calls.some(x=>x.url.includes('openai.com')));
 const stale=await scenario({version:id});assert.equal(stale.status,409);assert(!stale.calls.some(x=>x.url.includes('rpc/agent_execute_operator_plan')));
 assert.equal((await scenario({active:false})).status,403);const plain=await scenario({natural:true});assert.equal(plain.status,200);assert(plain.calls.some(x=>x.url.includes('rpc/agent_execute_operator_plan')));const many=await scenario({natural:true,planCount:2});assert.equal(many.status,409);assert(!many.calls.some(x=>x.url.includes('rpc/agent_execute_operator_plan')));assert.equal((await scenario({natural:true,planCount:0})).status,409);
 console.log('PASS: private pending plans, human-readable parameters, financial confirmation without model, exact revision, inactive/foreign chat denial');
})().catch(e=>{console.error(e);process.exitCode=1});
