do $test$
declare director uuid:=gen_random_uuid();foreman uuid:=gen_random_uuid();pid uuid:=gen_random_uuid();foreign_pid uuid:=gen_random_uuid();chat uuid:=gen_random_uuid();msg uuid:=gen_random_uuid();r jsonb;data jsonb;denied boolean;i integer;
begin begin
 insert into auth.users(id) values(director),(foreman);insert into public.profiles(id,role,is_active) values(director,'director',true),(foreman,'foreman',true);insert into public.agent_director_access values(director);insert into public.projects(id,name,responsible_user_id) values(pid,'TEST report scope',foreman),(foreign_pid,'TEST foreign report scope',null);insert into public.project_work_items(project_id,work_name,planned_volume) values(pid,'TEST visible report work',10),(foreign_pid,'TEST hidden report work',20);
 insert into public.agent_conversations(id,owner_id,title) values(chat,director,'TEST report quota');insert into public.agent_chat_messages(id,owner_id,chat_id,kind,content) values(msg,director,chat,'user','TEST report');
 execute 'set local role service_role';r:=public.agent_claim_report(director,msg,'statement',jsonb_build_object('project_id',pid));if public.agent_claim_report(director,msg,'statement',jsonb_build_object('project_id',pid)) is distinct from r then raise exception 'Report retry changed identity';end if;execute 'reset role';
 perform set_config('request.jwt.claim.sub',foreman::text,true);execute 'set local role authenticated';data:=public.get_existing_report_data('production',pid);if jsonb_array_length(data->'projectWorkItems')<>1 or data->'projects'->0 ? 'planned_revenue' then raise exception 'Production report leaks foreign/money';end if;
 denied:=false;begin perform public.get_existing_report_data('production',foreign_pid);exception when others then denied:=true;end;if not denied then raise exception 'Foreign production report';end if;
 denied:=false;begin perform public.get_existing_report_data('financial_metrics',pid);exception when others then denied:=sqlerrm='Report access denied';end;if not denied then raise exception 'Foreman financial report';end if;
 if exists(select 1 from public.agent_report_assets where owner_id=director) then raise exception 'Foreign report metadata';end if;execute 'reset role';
 for i in 1..19 loop msg:=gen_random_uuid();insert into public.agent_chat_messages(id,owner_id,chat_id,kind,content) values(msg,director,chat,'user','TEST quota');perform public.agent_claim_report(director,msg,'statement',jsonb_build_object('project_id',pid));end loop;
 msg:=gen_random_uuid();insert into public.agent_chat_messages(id,owner_id,chat_id,kind,content) values(msg,director,chat,'user','TEST quota denied');denied:=false;begin perform public.agent_claim_report(director,msg,'statement',jsonb_build_object('project_id',pid));exception when others then denied:=sqlerrm='Report quota: 20 per day';end;if not denied then raise exception 'Report quota failed';end if;
 if has_function_privilege('authenticated','public.agent_claim_report(uuid,uuid,text,jsonb)','execute') or has_function_privilege('anon','public.get_existing_report_data(text,uuid)','execute') then raise exception 'Report grants';end if;
 raise exception using errcode='P0992',message='ROLLBACK_REPORTS';exception when sqlstate 'P0992' then null;end;
end $test$;
select 'PASS: actual authenticated report scope, foreign/financial denial and safe columns, private owner metadata, closed claimer, identity/retry and daily quota; fixtures rolled back' result;
