do $test$
declare actor uuid:=gen_random_uuid();pid uuid:=gen_random_uuid();chat uuid:=gen_random_uuid();msg uuid;confirmation uuid;plan jsonb;r jsonb;cmd jsonb;project jsonb;denied boolean;k text;
begin begin
 insert into auth.users(id) values(actor);insert into public.profiles(id,role,is_active) values(actor,'finance',true);perform set_config('request.jwt.claim.sub',actor::text,true);insert into public.agent_conversations(id,owner_id,title) values(chat,actor,'TEST manual role parity');
 msg:=gen_random_uuid();insert into public.agent_chat_messages(id,owner_id,chat_id,kind,content) values(msg,actor,chat,'user','TEST finance create');execute 'set local role service_role';plan:=public.agent_prepare_operator_plan(actor,chat,msg,'project_create',jsonb_build_object('name','TEST finance card','contractor_company','ООО','planned_revenue',100));execute 'reset role';confirmation:=gen_random_uuid();insert into public.agent_chat_messages(id,owner_id,chat_id,kind,content) values(confirmation,actor,chat,'user','ПОДТВЕРЖДАЮ '||(plan->>'id'));execute 'set local role service_role';r:=public.agent_execute_operator_plan(actor,(plan->>'id')::uuid,(plan->>'revision')::uuid,confirmation);execute 'reset role';pid:=(r->'result'->'project'->>'id')::uuid;
 update public.profiles set role='accountant' where id=actor;select to_jsonb(p) into project from public.projects p where id=pid;
 msg:=gen_random_uuid();insert into public.agent_chat_messages(id,owner_id,chat_id,kind,content) values(msg,actor,chat,'user','TEST accountant edit');execute 'set local role service_role';plan:=public.agent_prepare_operator_plan(actor,chat,msg,'project_card_write',jsonb_build_object('action','update','id',pid,'expected',project,'values',jsonb_build_object('planned_revenue',150),'cost_changes','[]'::jsonb));execute 'reset role';confirmation:=gen_random_uuid();insert into public.agent_chat_messages(id,owner_id,chat_id,kind,content) values(confirmation,actor,chat,'user','ПОДТВЕРЖДАЮ '||(plan->>'id'));execute 'set local role service_role';r:=public.agent_execute_operator_plan(actor,(plan->>'id')::uuid,(plan->>'revision')::uuid,confirmation);execute 'reset role';if (r->'result'->'project'->>'planned_revenue')::numeric<>150 then raise exception 'Accountant card regression';end if;
 update public.profiles set role='manager' where id=actor;
 foreach k in array array['material','other_expense','subcontractor'] loop
  msg:=gen_random_uuid();insert into public.agent_chat_messages(id,owner_id,chat_id,kind,content) values(msg,actor,chat,'user','TEST manager create');cmd:=jsonb_build_object('kind',k,'action','create','values',jsonb_build_object('project_id',pid,'name','TEST manager '||k,'planned_amount',123));execute 'set local role service_role';plan:=public.agent_prepare_operator_plan(actor,chat,msg,'obligation_write',cmd);execute 'reset role';confirmation:=gen_random_uuid();insert into public.agent_chat_messages(id,owner_id,chat_id,kind,content) values(confirmation,actor,chat,'user','ПОДТВЕРЖДАЮ '||(plan->>'id'));execute 'set local role service_role';r:=public.agent_execute_operator_plan(actor,(plan->>'id')::uuid,(plan->>'revision')::uuid,confirmation);execute 'reset role';
  denied:=false;begin perform public.execute_obligation_command(gen_random_uuid(),jsonb_build_object('kind',k,'action','update','id',r->'result'->'record'->>'id','expected',r->'result'->'record','values',jsonb_build_object('planned_amount',999)));exception when others then denied:=sqlerrm='Financial access denied';end;if not denied then raise exception 'Manager gained financial edits';end if;
 end loop;
 update public.profiles set role='finance' where id=actor;select to_jsonb(p) into project from public.projects p where id=pid;cmd:=jsonb_build_object('action','delete','project_id',pid,'expected',project);r:=public.execute_project_delete(gen_random_uuid(),cmd||jsonb_build_object('expected_snapshot',public.preview_project_delete(cmd)));if r->>'verified'<>'true' or exists(select 1 from public.projects where id=pid) then raise exception 'Finance aggregate deletion regression';end if;
 update public.profiles set role='director' where id=actor;denied:=false;begin perform public.execute_financial_operation(gen_random_uuid(),jsonb_build_object('action','create','values',jsonb_build_object('operation_type','income','article','Оплата заказчика','payer_company','ООО','amount',1)));exception when others then denied:=sqlerrm='Trusted director required';end;if not denied then raise exception 'Untrusted director bypassed shared wrapper';end if;
 raise exception using errcode='P0992',message='ROLLBACK_ROLE_COMPAT';exception when sqlstate 'P0992' then null;end;
end $test$;
select 'PASS: finance creates, accountant edits, finance deletes through subject plans/shared commands; manager only creates permitted costs; untrusted director cannot bypass shared RPC; fixtures rolled back' result;
