do $test$
declare actor uuid:=gen_random_uuid();pid uuid:=gen_random_uuid();material uuid:=gen_random_uuid();project jsonb;cmd jsonb;snapshot jsonb;r jsonb;debt uuid;request uuid:=gen_random_uuid();denied boolean;chat uuid:=gen_random_uuid();msg uuid:=gen_random_uuid();confirmation uuid:=gen_random_uuid();plan jsonb;
begin
 begin
 insert into auth.users(id) values(actor);insert into public.profiles(id,role,is_active) values(actor,'director',true);insert into public.agent_director_access values(actor);perform set_config('request.jwt.claim.sub',actor::text,true);
 insert into public.projects(id,name,contractor_company) values(pid,'TEST atomic aggregate delete','ООО');insert into public.project_materials(id,project_id,name,actual_amount) values(material,pid,'TEST deferred material',75);
 r:=public.execute_credit_operation(gen_random_uuid(),jsonb_build_object('action','create','values',jsonb_build_object('operation_type','expense','article','ТМЦ','amount',250,'project_id',pid,'cost_item_id',material,'cost_item_type','material','credit_kind','material','counterparty','TEST supplier'),'credit',jsonb_build_object('due_date','2026-11-01','full_repayment_date','2026-11-01')));debt:=(r->'credit'->>'id')::uuid;
 perform public.execute_financial_operation(gen_random_uuid(),jsonb_build_object('action','create','values',jsonb_build_object('operation_type','expense','article','Погашение кредиторки','project_id',pid,'payable_id',debt,'amount',100)));
 perform public.execute_financial_operation(gen_random_uuid(),jsonb_build_object('action','create','values',jsonb_build_object('operation_type','income','article','Оплата заказчика','project_id',pid,'amount',500)));
 r:=public.execute_obligation_command(gen_random_uuid(),jsonb_build_object('kind','pto_record','action','create','values',jsonb_build_object('project_id',pid,'document_type','aosr','final_date','2026-11-01','status','requested')));perform public.execute_obligation_command(gen_random_uuid(),jsonb_build_object('kind','pto_record','action','update','id',r->'record'->>'id','expected',r->'record','values',jsonb_build_object('status','signed')));
 insert into public.project_team_members(project_id,user_id,team_role,is_active) values(pid,actor,'foreman',true);insert into public.project_work_sections(project_id,name) values(pid,'TEST deleted section');insert into public.project_work_items(project_id,work_name,planned_volume) values(pid,'TEST deleted work',100);
 select to_jsonb(p) into project from public.projects p where id=pid;cmd:=jsonb_build_object('action','delete','project_id',pid,'expected',project);snapshot:=public.preview_project_delete(cmd);if jsonb_array_length(snapshot->'operations')<>3 or not exists(select 1 from public.projects where id=pid) then raise exception 'Delete preview wrote or lost contents';end if;
 -- A new child after the manual preview must prevent any partial deletion.
 insert into public.project_work_tasks(project_id,title) values(pid,'TEST added concurrently');denied:=false;begin perform public.execute_project_delete(request,cmd||jsonb_build_object('expected_snapshot',snapshot));exception when others then denied:=sqlerrm='Project contents changed; create a new approval';end;if not denied or (select count(*) from public.operations where project_id=pid)<>3 then raise exception 'Delete stale or partial';end if;
 insert into public.agent_conversations(id,owner_id,title) values(chat,actor,'TEST delete');insert into public.agent_chat_messages(id,owner_id,chat_id,kind,content) values(msg,actor,chat,'user','TEST delete object');execute 'set local role service_role';plan:=public.agent_prepare_operator_plan(actor,chat,msg,'project_delete',cmd);execute 'reset role';
 insert into public.agent_chat_messages(id,owner_id,chat_id,kind,content) values(confirmation,actor,chat,'user','ПОДТВЕРЖДАЮ '||(plan->>'id'));execute 'set local role service_role';r:=public.agent_execute_operator_plan(actor,(plan->>'id')::uuid,(plan->>'revision')::uuid,confirmation);execute 'reset role';
 if r->'result'->>'verified'<>'true' or exists(select 1 from public.projects where id=pid) or exists(select 1 from public.operations where project_id=pid) or exists(select 1 from public.project_team_members where project_id=pid) or exists(select 1 from public.payables where id=debt) then raise exception 'Aggregate deletion incomplete';end if;
 execute 'set local role service_role';if public.agent_execute_operator_plan(actor,(plan->>'id')::uuid,(plan->>'revision')::uuid,confirmation) is distinct from r then raise exception 'Delete plan replay';end if;execute 'reset role';
 raise exception using errcode='P0992',message='ROLLBACK_AGGREGATE_DELETE';exception when sqlstate 'P0992' then null;end;
end $test$;
select 'PASS: real subject PTO create/status, deferred receipt and repayment, full deletion snapshot, concurrent child refusal without partial loss, exact agent confirmation/replay, aggregate cascades; fixtures rolled back' result;
