do $test$
declare actor uuid:=gen_random_uuid();employee uuid:=gen_random_uuid();event uuid:=gen_random_uuid();expense uuid:=gen_random_uuid();r jsonb;o jsonb;denied boolean;pid uuid:=gen_random_uuid();ip uuid:=gen_random_uuid();ar uuid:=gen_random_uuid();ar2 uuid:=gen_random_uuid();
begin begin
 insert into auth.users(id) values(actor);insert into public.profiles(id,role,is_active) values(actor,'finance',true);perform set_config('request.jwt.claim.sub',actor::text,true);
 insert into public.org_employees(id,name,company,monthly_salary) values(employee,'TEST salary','ООО',1000);insert into public.events(id,title,event_date,company,planned_amount) values(event,'TEST payment event','2026-10-07','ООО',2000);insert into public.org_expenses(id,name,company,monthly_amount) values(expense,'TEST organizational expense','ООО',3000);
 r:=public.execute_financial_operation(gen_random_uuid(),jsonb_build_object('action','create','values',jsonb_build_object('operation_type','expense','article','Орг. расходы','org_employee_id',employee,'payer_company','ООО','amount',21.25)));o:=r->'operation';
 r:=public.execute_financial_operation(gen_random_uuid(),jsonb_build_object('action','update','id',o->>'id','expected',o,'values',jsonb_build_object('org_employee_id',null,'org_event_id',event,'amount',34.5)));o:=r->'operation';if exists(select 1 from public.operations where org_employee_id=employee) or (select sum(amount) from public.operations where org_event_id=event)<>34.5 then raise exception 'Employee/event transfer';end if;
 r:=public.execute_financial_operation(gen_random_uuid(),jsonb_build_object('action','update','id',o->>'id','expected',o,'values',jsonb_build_object('org_event_id',null,'org_expense_id',expense,'amount',45.75)));o:=r->'operation';if exists(select 1 from public.operations where org_event_id=event) or (select sum(amount) from public.operations where org_expense_id=expense)<>45.75 then raise exception 'Event/expense transfer';end if;
 denied:=false;begin perform public.execute_obligation_command(gen_random_uuid(),jsonb_build_object('kind','event','action','delete','id',event,'expected',(select to_jsonb(e) from public.events e where id=event),'values','{}'::jsonb));exception when others then denied:=true;end;if denied then raise exception 'Unlinked event deletion wrongly blocked';end if;
 perform public.execute_financial_operation(gen_random_uuid(),jsonb_build_object('action','delete','id',o->>'id','expected',o,'values','{}'::jsonb));if exists(select 1 from public.operations where created_by=actor) then raise exception 'Organizational delete left payment';end if;
 insert into public.projects(id,name,contractor_company) values(pid,'TEST move ООО','ООО'),(ip,'TEST move ИП','ИП');insert into public.receivables(id,project_id,customer,amount) values(ar,pid,'TEST customer',1000),(ar2,ip,'TEST IP customer',1000);
 r:=public.execute_financial_operation(gen_random_uuid(),jsonb_build_object('action','create','values',jsonb_build_object('operation_type','income','article','Оплата заказчика','amount',99.99,'project_id',pid,'receivable_id',ar)));o:=r->'operation';
 r:=public.execute_financial_operation(gen_random_uuid(),jsonb_build_object('action','update','id',o->>'id','expected',o,'values',jsonb_build_object('project_id',ip,'receivable_id',ar2)));if r->'operation'->>'payer_company'<>'ИП' or (select paid_amount from public.receivables where id=ar)<>0 or (select paid_amount from public.receivables where id=ar2)<>99.99 then raise exception 'Cross-project debt/company transfer';end if;
 raise exception using errcode='P0992',message='ROLLBACK_ORG_LINKS';exception when sqlstate 'P0992' then null;end;
end $test$;
select 'PASS: employee → event → organization expense amount/link transfers, unlink/delete and cross-project company/AR recalculation to the cent; fixtures rolled back' result;
