const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const source=fs.readFileSync('supabase/functions/_shared/report-renderers.js','utf8').replace(/^export /gm,''),context={};vm.createContext(context);vm.runInContext(source,context);
const snapshot=JSON.parse(fs.readFileSync('tests/artifacts/financial-server-snapshot.json','utf8'));snapshot.projects[0].name='<script>leak()</script>';
const html=context.renderExistingReport('statement',snapshot,{project_id:snapshot.projects[0].id});assert(!/<script\b/i.test(html));assert(html.includes('&lt;script&gt;leak()&lt;/script&gt;'));assert(html.includes('Content-Security-Policy'));assert(html.includes('Себестоимость факт'));assert(html.includes('1\u00a0720')||html.includes('970'));
const month=context.renderExistingReport('organization_month',snapshot,{month:'2026-10',company:'all'});assert(month.includes('1\u00a0130'));assert(month.includes('670'));assert(!/<script\b/i.test(month));
const kp=context.renderExistingReport('proposals',{proposals:[{name:'TEST КП',status:'lost',lost_reason:'<img src=x onerror=leak()>',amount:1500}]},{});assert(kp.includes('TEST КП'));assert(!kp.includes('<img'));
const production=context.renderExistingReport('production',{projects:[{id:'p',name:'TEST production'}],projectWorkItems:[{id:'w',project_id:'p',work_name:'TEST work',unit:'м',planned_volume:100,completed_volume:23,status:'in_progress'}],projectWorkProgress:[{work_item_id:'w',progress_date:'2026-10-06',completed_volume:20}],projectWorkMaterials:[]},{project_id:'p',from:'2026-10-01',to:'2026-10-31'});assert(production.includes('TEST work'));assert(production.includes('20'));
fs.mkdirSync('tests/artifacts/reports',{recursive:true});for(const [name,text] of Object.entries({statement:html,month,proposals:kp,production}))fs.writeFileSync('tests/artifacts/reports/'+name+'.html',text);
console.log('PASS: four actual manual renderers, real financial snapshot values, exact dated production facts, escaped external names, no executable scripts, private print-ready HTML artifacts');

const legacyMonth=context.renderExistingReport('organization_month',{ops:[{operation_type:'income',amount:500,operation_date:'2026-10-06',payer_company:'ООО'},{operation_type:'credit',credit_kind:null,amount:75,operation_date:'2026-10-06',payer_company:'ООО'},{operation_type:'expense',credit_kind:'material',article:'ТМЦ',amount:250,operation_date:'2026-10-06',payer_company:'ООО'},{operation_type:'expense',article:'Погашение кредиторки',amount:100,operation_date:'2026-10-06',payer_company:'ООО'}]},{month:'2026-10',company:'all'});
assert(legacyMonth.replace(/\s*₽/g,'').includes('расходы 100; кредитные деньги 75; кредиты в форме ТМЦ/отсрочки 0; денежный результат 475'));
assert(!legacyMonth.includes('ТМЦ</td><td>250'));console.log('PASS: legacy unspecified credit is money, deferred material receipt excluded from monthly cash flow and cash expense categories');

const metrics=context.renderExistingReport('financial_metrics',snapshot,{project_id:snapshot.projects[0].id});assert.equal(metrics.card.income,130);assert.equal(metrics.card.operatingExpense,440);assert.equal(metrics.card.expense,460);assert.equal(metrics.card.receivable,1720);assert.equal(metrics.vat_registers[0].inputTotal,44);const txt=context.renderExistingReport('statement_text',snapshot,{project_id:snapshot.projects[0].id});assert(typeof txt==='string'&&txt.includes('1720')||txt.includes('1\u00a0720'));console.log('PASS: actual complete project metrics and quarter VAT register totals, existing TXT export');
