do $test$
declare director uuid:=gen_random_uuid();foreman uuid:=gen_random_uuid();project_id uuid:=gen_random_uuid();chat uuid;first jsonb;again jsonb;linked jsonb;result jsonb;hash text:=repeat('a',64);other text:=repeat('b',64);denied boolean;
begin begin
 insert into auth.users(id) values(director),(foreman);
 insert into public.profiles(id,role,is_active) values(director,'director',true),(foreman,'foreman',true);
 insert into public.agent_director_access values(director);
 insert into public.projects(id,name) values(project_id,'TEST Telegram project');
 insert into public.project_team_members(project_id,user_id,assigned_by) values(project_id,foreman,director);
 perform set_config('request.jwt.claim.sub',director::text,true);execute 'set local role authenticated';
 result:=public.telegram_begin_link(hash);execute 'reset role';if result->>'linked'<>'false' then raise exception 'Ticket unexpected prior link';end if;
 perform set_config('request.jwt.claim.role','service_role',true);execute 'set local role service_role';
 linked:=public.telegram_bridge('consume',jsonb_build_object('hash',hash,'telegram_user_id',901234567));
 if linked->>'linked'<>'true' then raise exception 'Director binding failed';end if;
 if public.telegram_bridge('consume',jsonb_build_object('hash',hash,'telegram_user_id',901234567))->>'linked'<>'false' then raise exception 'Ticket replay';end if;
 first:=public.telegram_bridge('enqueue',jsonb_build_object('update_id',4001,'telegram_user_id',901234567,'event','new_chat','update',jsonb_build_object('update_id',4001,'message',jsonb_build_object('chat',jsonb_build_object('id',901234567,'type','private'),'from',jsonb_build_object('id',901234567),'text','🆕 Новый чат'))));
 again:=public.telegram_bridge('enqueue',jsonb_build_object('update_id',4001,'telegram_user_id',901234567,'event','new_chat','update',jsonb_build_object('update_id',4001,'message',jsonb_build_object('chat',jsonb_build_object('id',901234567,'type','private'),'from',jsonb_build_object('id',901234567),'text','🆕 Новый чат'))));
 if first->>'duplicate'<>'false' or again->>'duplicate'<>'true' then raise exception 'Duplicate Telegram update changed state';end if;
 chat:=(first->>'chat_id')::uuid;
 result:=public.telegram_bridge('claim');if (result->>'update_id')::bigint<>4001 or result->>'chat_id'<>chat::text then raise exception 'Queue did not bind chat';end if;
 result:=public.telegram_save_incoming(4001,director,chat,'instruction','text','TEST Telegram request');
 if public.telegram_save_incoming(4001,director,chat,'instruction','text','TEST Telegram request')->>'id' is distinct from result->>'id' then raise exception 'Incoming replay duplicate';end if;
 if not public.telegram_verify_update(4001,director,chat,'instruction',(result->>'id')::uuid) then raise exception 'Internal identity not verified';end if;
 denied:=false;begin perform public.telegram_verify_update(4001,foreman,chat,'instruction',(result->>'id')::uuid);exception when others then denied:=true;end;if not denied and public.telegram_verify_update(4001,foreman,chat,'instruction',(result->>'id')::uuid) then raise exception 'Other owner accepted';end if;
 result:=public.telegram_save_transport_answer(4001,director,chat,'TEST Telegram answer');
 if public.telegram_save_transport_answer(4001,director,chat,'TEST Telegram answer')->>'id' is distinct from result->>'id' then raise exception 'Answer replay duplicate';end if;
 perform public.telegram_bridge('finish',jsonb_build_object('update_id',4001,'result',jsonb_build_object('processed',true),'answer',jsonb_build_object('method','sendMessage','chat_id',901234567,'text','TEST Telegram answer')));
 result:=public.telegram_bridge('claim_outbox');if (result->>'update_id')::bigint<>4001 then raise exception 'Outbox absent';end if;
 execute 'reset role';perform set_config('request.jwt.claim.role','authenticated',true);
 perform set_config('request.jwt.claim.sub',foreman::text,true);execute 'set local role authenticated';result:=public.telegram_begin_link(other);execute 'reset role';
 perform set_config('request.jwt.claim.role','service_role',true);execute 'set local role service_role';linked:=public.telegram_bridge('consume',jsonb_build_object('hash',other,'telegram_user_id',901234568));if linked->>'linked'<>'true' then raise exception 'Foreman binding failed';end if;
 result:=public.telegram_bridge('get_link',jsonb_build_object('telegram_user_id',901234568));if result->>'role'<>'foreman' then raise exception 'Foreman role';end if;
 if public.telegram_bridge('choose_project',jsonb_build_object('owner_id',foreman,'telegram_user_id',901234568,'project_id',project_id,'generation',result->'generation')) is distinct from 'true'::jsonb then raise exception 'Assigned project denied';end if;
 update public.profiles set is_active=false where id=foreman;
 if public.telegram_bridge('get_link',jsonb_build_object('telegram_user_id',901234568)) is not null then raise exception 'Disabled foreman retained access';end if;
 execute 'reset role';perform set_config('request.jwt.claim.role','authenticated',true);perform set_config('request.jwt.claim.sub',director::text,true);execute 'set local role authenticated';
 if not public.telegram_disconnect() then raise exception 'Disconnect failed';end if;execute 'reset role';
 if exists(select 1 from voltmaster_private.telegram_links where owner_id=director) then raise exception 'Disconnect left link';end if;
 raise exception using errcode='P0994',message='ROLLBACK_TELEGRAM_TEST';exception when sqlstate 'P0994' then null;end;
end $test$;
select 'PASS: one-use hashed links, director/foreman roles, chat snapshot, duplicate queue, idempotent transcript/answer/outbox, disabled access and disconnect; fixtures rolled back' result;
